version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1q2w3e4r
    depends_on:
      - db
    networks:
      - demodockercurso_my-network

  db:
    hostname: db
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - demodockercurso_my-network

networks:
  demodockercurso_my-network:

volumes:
  db_data:
